[package]
name = "parser-benchmark"
version = "0.1.0"
edition = "2024"

[dependencies]
html5ever = "0.35"
markup5ever_rcdom = "0.35"
astral-tl = "0.7.9"

[[bin]]
name = "parser_benchmark"
path = "parser_benchmark.rs"
